# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be4497e33aefe975baa11fb7605fa11bcdf6bebb06da0bbc8f2394f815ab93a2458794b6472531a1b43d3c6d8d4c48a2e795649e65e100afaf9bedbc00d99685

test:
  secret_key_base: aacf322accbf26680465b7a1e8248e482e05619335528ea7782e606b485b4a57bcf3e9b53fbfa6c9b6d67a73b8dce64fb6c782e44af5bbbff017eb04f31f813f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
